setwd("../downloads/Exploratory Data Analysis/exdata%2Fdata%2Fhousehold_power_consumption")
HPC <- read.table("household_power_consumption.txt",sep = ";",header = TRUE,na.strings = "?")
HPCS <- subset(HPC,Date == "1/2/2007" | Date == "2/2/2007")
HPCS$dt <- strptime(paste(HPCS$Date,HPCS$Time),"%d/%m/%Y %h:%m:%s")
plot(HPCS$dt,HPCS$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering")
points(HPCS$dt,HPCS$Sub_metering_2,type="l",col="Red")
points(HPCS$dt,HPCS$Sub_metering_3,type="l",col="Blue")
legend("topright",lty = 1,col=c("Black","Red","Blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,"plot3.png",height=480,width=480)
dev.off()
